---
name: Code lint yaml (yamllint)
on:
  push:
    paths:
      - '.github/workflows/*.yml'

jobs:
  format:
    runs-on: ubuntu-24.04
    env:
      TERM: xterm-256color
    steps:
      - uses: actions/checkout@v2
      - name: Validate yaml files
        run: cd .github/workflows/ && yamllint *
