name: ctest-windows
on:
  push:
    paths:
      - '.github/workflows/ctest-windows.yml'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - '**.s'
      - '**.hpp'
      - '**.cpp'

jobs:
  tests:
    name: ctest-windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache LLVM and Clang
        uses: actions/cache@v2
        with:
          path: C:/Program Files/LLVM
          key: llvm-12
      - name: Install LLVM and Clang
        run: choco install llvm
      - name: Build tests
        run: |
          cmake -B build -S .tests -DCMAKE_CXX_COMPILER="C:\Program Files\LLVM\bin\clang++.exe"
          cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --timeout 1 --output-on-failure
