name: CTest (Windows)
on:
  push:
    paths:
      - '.github/workflows/ctest-windows.yml'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - '**.hpp'
      - '**.cpp'
jobs:
  ctest:
    runs-on: windows-2022
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build tests
        run: |
          # The Generic CMake system name is used to skip ABI checks on the compiler
          cmake -B build -S .tests -G "Unix Makefiles" -DCMAKE_SYSTEM_NAME="Generic" -DCMAKE_CXX_COMPILER="clang++.exe"
          cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --timeout 1 --output-on-failure
