name: ctest-windows
on:
  push:
    paths:
      - '.github/workflows/ctest-windows.yml'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - '**.s'
      - '**.hpp'
      - '**.cpp'

jobs:
  tests:
    name: ctest-windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache LLVM and Clang
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-12
      - name: Install LLVM and Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: "13.0"
      - name: Build tests
        run: |
          cmake -B build -S .tests -DCMAKE_CXX_COMPILER=clang++
          cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --timeout 1 --output-on-failure
