name: CTest (macOS)
on:
  push:
    paths:
      - '.github/workflows/ctest-macos.yml'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - '**.hpp'
      - '**.cpp'
jobs:
  ctest:
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
    env:
      TERM: xterm-256color
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build tests
        run: |
          cmake -B build -S .tests
          cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --timeout 1 --output-on-failure
