---
name: Linux (gcc-14)
on:
  push:
    paths:
      - '.github/workflows/linux-gcc.yml'
      - 'CMakeLists.txt'
      - '**.cmake'
      - '**.hpp'
      - '**.cpp'
jobs:
  ctest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      TERM: xterm-256color
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build tests
        run: |
          cmake -B build -DCMAKE_CXX_COMPILER=g++-14
          cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --timeout 1 --output-on-failure
