---
name: MacOS (clang-18)
on:
  push:
    paths:
      - '.github/workflows/macos-clang.yml'
      - 'CMakeLists.txt'
      - '**.cmake'
      - '**.hpp'
      - '**.cpp'
jobs:
  ctest:
    runs-on: macos-15
    strategy:
      fail-fast: false
    env:
      TERM: xterm-256color
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build tests
        run: |
          cmake -B build -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@18)/bin/clang++
          cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --timeout 1 --output-on-failure
