name: ctest
on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - '**.hpp'
      - '**.cpp'

jobs:
  tests:
    name: ctest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    env:
      TERM: xterm-256color
    steps:
      - uses: actions/checkout@v2
      - name: Build tests
        run: |
          cmake -B build -S .tests
          cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --timeout 1 --output-on-failure
